name: Download a PR artifact
description: Store and share artifacts within GitHub Pull Requests.
author: inlet
inputs:
  github_token:
    description: GitHub Personal Access Token
    required: false
    default: ${{ github.token }}
  pr:
    description: GitHub Pull Request number
    required: false
    default: ${{ github.event.pull_request.number }}
  repo:
    description: Repository name with owner (like actions/checkout)
    required: false
    default: ${{ github.repository }}
  worfklow_file_name:
    description: The name of the workflow (like ci.yml)
    required: true
  artifact_name:
    description: The name of the artifact (like my-artifact)
    required: true
  path:
    description: Where to unpack the artifact
    required: false
    default: "./"
runs:
  using: node12
  main: main.js
